# Generated by Django 3.0.3 on 2020-05-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tocsoda', '0002_auto_20200525_0228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='free_best',
            new_name='FreeBest',
        ),
        migrations.RenameModel(
            old_name='web_best',
            new_name='WebBest',
        ),
    ]
