# Generated by Django 3.0.3 on 2020-05-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaybest',
            name='hour',
        ),
    ]
