# Generated by Django 3.0.3 on 2020-05-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joara', '0002_remove_todaybest_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaybest',
            name='day',
        ),
        migrations.RemoveField(
            model_name='todaybest',
            name='month',
        ),
        migrations.RemoveField(
            model_name='todaybest',
            name='year',
        ),
        migrations.AddField(
            model_name='todaybest',
            name='author',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todaybest',
            name='date',
            field=models.CharField(default='99999999', max_length=10),
            preserve_default=False,
        ),
    ]
