# Generated by Django 3.0.3 on 2020-05-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joara', '0003_auto_20200519_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaybest',
            name='author',
        ),
    ]
